# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c32be62efec6ee0b568b9f2781f01b6de6888a09f0743b579e349262bdb9151c4462c3d4aba3d811f286a092b0b8d8a782f7483a85d55ca15cf812d56fe0043

test:
  secret_key_base: 547016671a0242820c8e8d9374f5d3f297afee08e153cdedb335f4f2028ae80367ad834f5d60cc935a5b99894736e64496310299d10e5dee9d2a7c1a8ac9466b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
